# Any time that we're making use of docker,
# we need super user level permission 
# in order to execute.
sudo: required
services:
  - docker

# a series of different commands that get executed 
# before eiter deploy our project or our tests are ran.
before_install:
  - docker build -t winglesswind/docker-react -f Dockerfile.dev . 

# all the different commands that need to be executed 
# to actually run our test suites.
scripts:
  - docker run -e CI=true winglesswind/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  # From: http://testdockerreact-env.eba-bpj3hmfz.us-east-2.elasticbeanstalk.com/
  region: "us-east-2"
  app: "test-docker-react"
  env: "Testdockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-126052845425"
  # bucket_path should be exactly same as app name.
  bucket_path: "test-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
